version: '2'
services:
  nginx:
    image: packageman/nginx:1.0.0
    ports:
      - "80:80"
    volumes:
      - ../src:/src
      - ./nginx/conf:/etc/nginx/conf.d
    links:
      - php
      - redis
      - mongodb
    restart: always
  php:
    image: packageman/php-supervisor-node-sass:1.0.0
    volumes:
      - ../src:/src
      - ./php-supervisor-node-sass/supervisor/conf:/etc/supervisor/conf.d
    restart: always
  redis:
    image: packageman/redis:1.0.0
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
    restart: always
  mongodb:
    image: packageman/mongodb:1.0.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/var/lib/mongodb
    restart: always
volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local