version: '2'
services:
  nginx:
    image: packageman/nginx:1.10.1
    hostname: nginx
    ports:
      - "80:80"
    volumes:
      - ../src:/src
      - ./nginx/conf:/etc/nginx/conf.d
    links:
      - php
      - redis
      - mongodb
    restart: always
  php:
    image: packageman/php-supervisor-node-sass:1.0.1
    hostname: php
    volumes:
      - /etc/nginx/site-enabled:/etc/nginx/site-enabled
      - ../src:/src
      - ../deploy:/deploy
      - ./php-supervisor-node-sass/supervisor/conf:/etc/supervisor/conf.d
      - ./php-supervisor-node-sass/bin:/root/bin
    env_file: ./php-supervisor-node-sass/envfiles/stage.env
    restart: always
  redis:
    image: packageman/redis:3.0.7
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis
    restart: always
  mongodb:
    image: packageman/mongodb:3.2.7
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/var/lib/mongodb
    restart: always
volumes:
  mongodb-data:
    driver: local
  redis-data:
    driver: local
